### ISSUE TITLE
Ignore SWRL rules

### ISSUE THREAD

**Issue by balhoff** [andrewdbate/Sequoia#1]
Currently Sequoia exits with an error when it encounters a SWRL rule in an ontology:

```
An error occurred during reasoning: SWRLRule cannot be converted to Axiom.
```

It would be more convenient if it ignored these axioms and just logged a warning.

Example ontology: http://purl.obolibrary.org/obo/hp.owl

**Comment by andrewdbate** [comment]
Thanks for reporting the issue. I'll look into the example and get back to you shortly.
Andrew

**Comment by andrewdbate** [comment]
Now when Sequoia is used via the OWL API, the reasoner configuration allows for unsupported features (including SWRL rules) to be ignored.

From the CLI, a new command-line option allows for unsupported features to be ignored. Type `sequoia help classify` for more information.

From within Protégé, SWRL rules are now ignored but warnings are logged in the user interface (which is the same behaviour as for other unsupported features before this fix).

If you encounter any other problems, please do let me know.

**Comment by balhoff** [comment]
Great, thank you!
